### PR TITLE
Simplified Chinese Translation / 简体中文翻译

### PR DESCRIPTION
**Pull request by HaloSense**
Added a little bit of Chinese (Simplified) translation. We do have a Chinese (Traditional) translation in the pull request list but that one doesn't look legit and there seems to be some AI translation involved. (Correct me if I'm wrong)

This pull request will remain a draft and be continuously maintained **until all translations are finished and decided**. Please directly commit to this pull request branch to avoid redundant pull requests. Refer to my other repos for my previous translation works.

添加了少量（其实只有几行）简体中文翻译。库里现在有一个繁体中文翻译的PR，但是有少量机翻痕迹。

这个PR在所有内容翻译结束并校对完成之前将一直保持draft状态。请直接向本PR进行commit防止出现冗余PR。关于我过往参与的翻译工作，请参见我其他的库。

### CODE REVIEW

**Comment by HaloSense** [comment]
WIP: Just tested the part that has been translated, and some Chinese characters cannot display properly.

待修复：刚刚测试了一部分已完成翻译的文本，发现有一些汉字不能正常显示

**Comment by 0thElement** [comment]
It seems I'll have to include a separate font for simplified Chinese. I'll comment here again when that's available.

**Comment by HaloSense** [comment]
> It seems I'll have to include a separate font for simplified Chinese. I'll comment here again when that's available.

Gotcha. Much appreciated.

**Comment by HaloSense** [comment]
Probably should wait until a viable font is chosen.

**Comment by 0thElement** [comment]
I've added the font to the project. You can try it again ([link to commit](https://github.com/Arcthesia/ArcCreate/commits/master/c18e8de84389568476b557041199ae54d85838ae))

**Comment by HaloSense** [comment]
Thanks, been busy these days, trying it out now.

**Comment by HaloSense** [comment]
Wait how do i test?

**Comment by 0thElement** [comment]
What are you having trouble with exactly?

**Comment by HaloSense** [comment]
> What are you having trouble with exactly?

Never mind, I got dumb

**Comment by HaloSense** [comment]
Tested it out and everything looks fine, no visible character glitches.

That being said, the font is slightly different from that we normally would use. Some characters look slightly different. I wonder if i find a better font, can I and how do I replace it with the one in the repo?

**Comment by 0thElement** [comment]
You can only edit the font with unity editor. Just leave a link here and i can download it myself (make sure to check the font's license)

**Comment by 0thElement** [comment]
I've merged your changes. Thank you for contributing!

**Pull request closed without merging**
